[project]
name = "pavi-api"
version = "0.7.0"
description = "PAVI API component"
readme = "README.md"
authors = [
    {name = "Manuel Luypaert", email = "luypaert@ebi.ac.uk"}
]

requires-python = "==3.12.*"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]==0.133.*",
    "smart-open[s3]==7.3.*"
]

[project.optional-dependencies]
test = [
    "flake8==7.3.*",
    "flake8-unused-arguments==0.0.*",
    "mypy==1.18.*",
    "pytest==9.0.*",
    "pytest-cov==7.0.*",
    "pytest-mock==3.15.*",
    "httpx==0.28.*"
]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = [
    "boto3.*",
    "botocore.*",
    "smart_open.*"
]
ignore_missing_imports = true
